### ISSUE TITLE
Potential for trouble with pipeline stages

### ISSUE THREAD

**Issue by davidkellerman** [nxus/pipeliner#2]
In putting together [a recent PR](https://github.com/nxus/pipeliner/pull/1), I noticed that the handling of pipeline stages allows for some dubious programming patterns:
1. `Piperliner#stages` actually adds to existing stages, rather than replacing them, so any previously-defined stages, and tasks associated with them, remain active. (However, it looks like re-adding a previously-defined stage will remove any prior tasks, and, presumably, change the stage's sequence.)
2. `Pipeliner#task` will implicitly add a stage if it is not already defined.
The interface would be simpler and less error-prone if pipeline stages were allowed as an optional argument to the constructor, `Pipeliner#stages` were eliminated, and `Pipeliner#task` threw an error if the caller referred to an undefined stage. That is, treat stages as part of the initial definition of the pipeline, rather than something that is mutable.

**Comment by alexjreich** [comment]
@davidkellerman 

Re #1 I don’t have a preference.  I think we should probably replace the default set of stages with an empty pipeline, and having an optional arg for stages on pipeline creation makes sense and reduces lines of code.  I think it is helpful to have a way to add stages during runtime without having to recreate the entire pipeline however.  Immutability doesn’t really give us anything when we explicitly want/need to be able to update the pipeline stages/tasks after instantiation?

Re #2: what error conditions does this cause? This is a convenient shorthand when you are creating a pipeline with multiple stages that have a single task.  Why would an exception help you in any way? E.g. what would I ever do other than catch the exception and create a new stage?

**Comment by davidkellerman** [comment]
I always worry about undetected "undefined variables," because they're hard to troubleshoot, and typos in stage names are a variant of that. 

It wasn't clear to me that you _intended_ to accommodate the pattern of adding pipeline stages implicitly through Pipeliner#task. If so, it would be good to illustrate through an example. 

So you have two patterns: (1) define the stages up front, then fill in tasks; (2) define stages implicitly as tasks are defined. For (1), there's an _opportunity_ to catch typos in stage names, but that then interferes with (2). 

My model for Pipeliner was "build it, then use it," and I couldn't come up with use cases where I'd want to distribute the build (i.e. separate pieces of code each append stages to the pipeline). My reaction was, "ooh, that seems like trouble," since tasks are likely to be pretty tightly coupled. 

However, you're the one who saw the need for Pipeliner, so you presumably have a more nuanced view.

**Comment by alexjreich** [comment]
Closing as stages have been removed in 4.0
